#!/usr/bin/env bash
#
# Simple plugin to allow deploying of tar archives wo using
# a complete git repository or the heroku workflow
#
# Author: Gianluca Pacchiella <gp@ktln2.org>
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

case "$1" in
  tgz)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    verify_app_name "$2"
    APP="$2";
    # clean up after ourselves
    TMP_WORK_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_WORK_DIR" > /dev/null' RETURN

  chmod 755 $TMP_WORK_DIR
  unset GIT_DIR GIT_WORK_TREE
  pushd $TMP_WORK_DIR > /dev/null


    cat | tar xz -C "${TMP_WORK_DIR}"
    dokku receive "$APP" "buildstep" "$TMP_WORK_DIR" | sed -u "s/^/"$'\e[1G'"/"

    ;;

  help)
    cat && cat<<EOF
    tgz <app>                                     Deploy the compressed archive passed from stdin"
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
